# Generated by Django 4.2.4 on 2023-09-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.PositiveBigIntegerField(verbose_name="ID пользователя в тг"),
                ),
                ("name", models.TextField(verbose_name="Имя пользователя")),
                (
                    "uniq_name",
                    models.TextField(verbose_name="Уникальное имя пользователя"),
                ),
            ],
            options={"verbose_name": "Профиль",},
        ),
    ]
