# Generated by Django 4.2 on 2023-10-29 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("botModels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
    ]
