# Generated by Django 4.2 on 2023-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botModels", "0002_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.TextField(default="None", verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="external_id",
            field=models.PositiveBigIntegerField(
                unique=True, verbose_name="ID пользователя в тг"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.TextField(verbose_name="Имя пользователя в тг"),
        ),
    ]
