# Generated by Django 4.2 on 2023-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botModels", "0007_alter_products_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(max_length=4096, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Цена"),
        ),
    ]
