# Generated by Django 4.2 on 2023-11-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botModels", "0008_alter_products_description_alter_products_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(max_length=1024, verbose_name="Описание"),
        ),
    ]
