# Generated by Django 4.2 on 2023-11-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botModels", "0009_alter_products_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="description",
        ),
        migrations.RemoveField(
            model_name="products",
            name="name",
        ),
        migrations.AddField(
            model_name="products",
            name="description_ru",
            field=models.TextField(
                default="Описание", max_length=1024, verbose_name="Описание на русском"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="description_uz",
            field=models.TextField(
                default="Описание",
                max_length=1024,
                verbose_name="Описание на узбекском",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="name_ru",
            field=models.CharField(
                default="Имя", max_length=256, verbose_name="Название на русском"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="name_uz",
            field=models.CharField(
                default="Имя", max_length=256, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="language_code",
            field=models.CharField(default="ru", max_length=4, verbose_name="Язык"),
        ),
    ]
