reg_user_lang_code = {} # Форма для регистрации юзера
user_state         = {} # Основное состояние юзера
catalog            = () # Название кнопок в каталоге
all_products       = () # Название кнопок с карточками продуктов
last_category      = {} # 
last_product       = {} #
count_products     = {} #
expand_message     = {} # Состояние сообщения
# user_menu_page   = {} # состаяне юзеру в меню кокрзины